# Generated by Django 4.2.2 on 2023-06-21 13:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_trendingitemcategory_alter_brand_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='CartItems',
        ),
    ]
